apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-updates
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/dev/go
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
